//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 

using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;

#pragma warning disable 1591

namespace Dataifx.AuctionDesc.Services.Web_References.WSDisconnect {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="PlataformaWebSoap", Namespace="http://tempuri.org/")]
    public partial class PlataformaWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PortafolioClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovimientoGraficoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovimientoIGBCOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovimientoCOLCAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovimientoCOL20OperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneCuentasDecevalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerOrdenesAbiertasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerOrdenesDiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPyPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSegmentosComisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerParametrosConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCierresPorInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitudDeCancelaciónOperationCompleted;
        
        private System.Threading.SendOrPostCallback ColocarOrdenOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarContraseñaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSaldoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesconexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstaConectadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PlataformaWeb() {
            this.Url = global::Dataifx.AuctionDesc.Services.Properties.Settings.Default.Dataifx_Trading_Services_WSDisconnect_PlataformaWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccionesCompletedEventHandler AccionesCompleted;
        
        /// <remarks/>
        public event PortafolioClienteCompletedEventHandler PortafolioClienteCompleted;
        
        /// <remarks/>
        public event MovimientoGraficoCompletedEventHandler MovimientoGraficoCompleted;
        
        /// <remarks/>
        public event MovimientoIGBCCompletedEventHandler MovimientoIGBCCompleted;
        
        /// <remarks/>
        public event MovimientoCOLCAPCompletedEventHandler MovimientoCOLCAPCompleted;
        
        /// <remarks/>
        public event MovimientoCOL20CompletedEventHandler MovimientoCOL20Completed;
        
        /// <remarks/>
        public event AutenticacionCompletedEventHandler AutenticacionCompleted;
        
        /// <remarks/>
        public event ObtieneCuentasDecevalCompletedEventHandler ObtieneCuentasDecevalCompleted;
        
        /// <remarks/>
        public event ObtenerOrdenesAbiertasCompletedEventHandler ObtenerOrdenesAbiertasCompleted;
        
        /// <remarks/>
        public event ObtenerOrdenesDiaCompletedEventHandler ObtenerOrdenesDiaCompleted;
        
        /// <remarks/>
        public event ObtenerPyPCompletedEventHandler ObtenerPyPCompleted;
        
        /// <remarks/>
        public event ObtenerSegmentosComisionCompletedEventHandler ObtenerSegmentosComisionCompleted;
        
        /// <remarks/>
        public event ObtenerParametrosConfiguracionCompletedEventHandler ObtenerParametrosConfiguracionCompleted;
        
        /// <remarks/>
        public event ObtenerCierresPorInstrumentoCompletedEventHandler ObtenerCierresPorInstrumentoCompleted;
        
        /// <remarks/>
        public event SolicitudDeCancelaciónCompletedEventHandler SolicitudDeCancelaciónCompleted;
        
        /// <remarks/>
        public event ColocarOrdenCompletedEventHandler ColocarOrdenCompleted;
        
        /// <remarks/>
        public event CambiarContraseñaCompletedEventHandler CambiarContraseñaCompleted;
        
        /// <remarks/>
        public event ObtenerSaldoClienteCompletedEventHandler ObtenerSaldoClienteCompleted;
        
        /// <remarks/>
        public event DesconexionCompletedEventHandler DesconexionCompleted;
        
        /// <remarks/>
        public event EstaConectadoCompletedEventHandler EstaConectadoCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/Acciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Acciones() {
            object[] results = this.Invoke("Acciones", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void AccionesAsync() {
            this.AccionesAsync(null);
        }
        
        /// <remarks/>
        public void AccionesAsync(object userState) {
            if ((this.AccionesOperationCompleted == null)) {
                this.AccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccionesOperationCompleted);
            }
            this.InvokeAsync("Acciones", new object[0], this.AccionesOperationCompleted, userState);
        }
        
        private void OnAccionesOperationCompleted(object arg) {
            if ((this.AccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccionesCompleted(this, new AccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/PortafolioCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PortafolioCliente(string idcliente) {
            object[] results = this.Invoke("PortafolioCliente", new object[] {
                        idcliente});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PortafolioClienteAsync(string idcliente) {
            this.PortafolioClienteAsync(idcliente, null);
        }
        
        /// <remarks/>
        public void PortafolioClienteAsync(string idcliente, object userState) {
            if ((this.PortafolioClienteOperationCompleted == null)) {
                this.PortafolioClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPortafolioClienteOperationCompleted);
            }
            this.InvokeAsync("PortafolioCliente", new object[] {
                        idcliente}, this.PortafolioClienteOperationCompleted, userState);
        }
        
        private void OnPortafolioClienteOperationCompleted(object arg) {
            if ((this.PortafolioClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PortafolioClienteCompleted(this, new PortafolioClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/MovimientoGrafico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] MovimientoGrafico(string nemotecnico) {
            object[] results = this.Invoke("MovimientoGrafico", new object[] {
                        nemotecnico});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void MovimientoGraficoAsync(string nemotecnico) {
            this.MovimientoGraficoAsync(nemotecnico, null);
        }
        
        /// <remarks/>
        public void MovimientoGraficoAsync(string nemotecnico, object userState) {
            if ((this.MovimientoGraficoOperationCompleted == null)) {
                this.MovimientoGraficoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovimientoGraficoOperationCompleted);
            }
            this.InvokeAsync("MovimientoGrafico", new object[] {
                        nemotecnico}, this.MovimientoGraficoOperationCompleted, userState);
        }
        
        private void OnMovimientoGraficoOperationCompleted(object arg) {
            if ((this.MovimientoGraficoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovimientoGraficoCompleted(this, new MovimientoGraficoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/MovimientoIGBC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] MovimientoIGBC() {
            object[] results = this.Invoke("MovimientoIGBC", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void MovimientoIGBCAsync() {
            this.MovimientoIGBCAsync(null);
        }
        
        /// <remarks/>
        public void MovimientoIGBCAsync(object userState) {
            if ((this.MovimientoIGBCOperationCompleted == null)) {
                this.MovimientoIGBCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovimientoIGBCOperationCompleted);
            }
            this.InvokeAsync("MovimientoIGBC", new object[0], this.MovimientoIGBCOperationCompleted, userState);
        }
        
        private void OnMovimientoIGBCOperationCompleted(object arg) {
            if ((this.MovimientoIGBCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovimientoIGBCCompleted(this, new MovimientoIGBCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/MovimientoCOLCAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] MovimientoCOLCAP() {
            object[] results = this.Invoke("MovimientoCOLCAP", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void MovimientoCOLCAPAsync() {
            this.MovimientoCOLCAPAsync(null);
        }
        
        /// <remarks/>
        public void MovimientoCOLCAPAsync(object userState) {
            if ((this.MovimientoCOLCAPOperationCompleted == null)) {
                this.MovimientoCOLCAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovimientoCOLCAPOperationCompleted);
            }
            this.InvokeAsync("MovimientoCOLCAP", new object[0], this.MovimientoCOLCAPOperationCompleted, userState);
        }
        
        private void OnMovimientoCOLCAPOperationCompleted(object arg) {
            if ((this.MovimientoCOLCAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovimientoCOLCAPCompleted(this, new MovimientoCOLCAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/MovimientoCOL20", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] MovimientoCOL20() {
            object[] results = this.Invoke("MovimientoCOL20", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void MovimientoCOL20Async() {
            this.MovimientoCOL20Async(null);
        }
        
        /// <remarks/>
        public void MovimientoCOL20Async(object userState) {
            if ((this.MovimientoCOL20OperationCompleted == null)) {
                this.MovimientoCOL20OperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovimientoCOL20OperationCompleted);
            }
            this.InvokeAsync("MovimientoCOL20", new object[0], this.MovimientoCOL20OperationCompleted, userState);
        }
        
        private void OnMovimientoCOL20OperationCompleted(object arg) {
            if ((this.MovimientoCOL20Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovimientoCOL20Completed(this, new MovimientoCOL20CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/Autenticacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Autenticacion(string idUsuario, string clave) {
            object[] results = this.Invoke("Autenticacion", new object[] {
                        idUsuario,
                        clave});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void AutenticacionAsync(string idUsuario, string clave) {
            this.AutenticacionAsync(idUsuario, clave, null);
        }
        
        /// <remarks/>
        public void AutenticacionAsync(string idUsuario, string clave, object userState) {
            if ((this.AutenticacionOperationCompleted == null)) {
                this.AutenticacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticacionOperationCompleted);
            }
            this.InvokeAsync("Autenticacion", new object[] {
                        idUsuario,
                        clave}, this.AutenticacionOperationCompleted, userState);
        }
        
        private void OnAutenticacionOperationCompleted(object arg) {
            if ((this.AutenticacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticacionCompleted(this, new AutenticacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtieneCuentasDeceval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtieneCuentasDeceval(string idUsuario) {
            object[] results = this.Invoke("ObtieneCuentasDeceval", new object[] {
                        idUsuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneCuentasDecevalAsync(string idUsuario) {
            this.ObtieneCuentasDecevalAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void ObtieneCuentasDecevalAsync(string idUsuario, object userState) {
            if ((this.ObtieneCuentasDecevalOperationCompleted == null)) {
                this.ObtieneCuentasDecevalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneCuentasDecevalOperationCompleted);
            }
            this.InvokeAsync("ObtieneCuentasDeceval", new object[] {
                        idUsuario}, this.ObtieneCuentasDecevalOperationCompleted, userState);
        }
        
        private void OnObtieneCuentasDecevalOperationCompleted(object arg) {
            if ((this.ObtieneCuentasDecevalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneCuentasDecevalCompleted(this, new ObtieneCuentasDecevalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerOrdenesAbiertas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerOrdenesAbiertas(string idusuario) {
            object[] results = this.Invoke("ObtenerOrdenesAbiertas", new object[] {
                        idusuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerOrdenesAbiertasAsync(string idusuario) {
            this.ObtenerOrdenesAbiertasAsync(idusuario, null);
        }
        
        /// <remarks/>
        public void ObtenerOrdenesAbiertasAsync(string idusuario, object userState) {
            if ((this.ObtenerOrdenesAbiertasOperationCompleted == null)) {
                this.ObtenerOrdenesAbiertasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerOrdenesAbiertasOperationCompleted);
            }
            this.InvokeAsync("ObtenerOrdenesAbiertas", new object[] {
                        idusuario}, this.ObtenerOrdenesAbiertasOperationCompleted, userState);
        }
        
        private void OnObtenerOrdenesAbiertasOperationCompleted(object arg) {
            if ((this.ObtenerOrdenesAbiertasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerOrdenesAbiertasCompleted(this, new ObtenerOrdenesAbiertasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerOrdenesDia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerOrdenesDia(string idusuario) {
            object[] results = this.Invoke("ObtenerOrdenesDia", new object[] {
                        idusuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerOrdenesDiaAsync(string idusuario) {
            this.ObtenerOrdenesDiaAsync(idusuario, null);
        }
        
        /// <remarks/>
        public void ObtenerOrdenesDiaAsync(string idusuario, object userState) {
            if ((this.ObtenerOrdenesDiaOperationCompleted == null)) {
                this.ObtenerOrdenesDiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerOrdenesDiaOperationCompleted);
            }
            this.InvokeAsync("ObtenerOrdenesDia", new object[] {
                        idusuario}, this.ObtenerOrdenesDiaOperationCompleted, userState);
        }
        
        private void OnObtenerOrdenesDiaOperationCompleted(object arg) {
            if ((this.ObtenerOrdenesDiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerOrdenesDiaCompleted(this, new ObtenerOrdenesDiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerPyP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerPyP(string nemotecnico, string tiponegocio) {
            object[] results = this.Invoke("ObtenerPyP", new object[] {
                        nemotecnico,
                        tiponegocio});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPyPAsync(string nemotecnico, string tiponegocio) {
            this.ObtenerPyPAsync(nemotecnico, tiponegocio, null);
        }
        
        /// <remarks/>
        public void ObtenerPyPAsync(string nemotecnico, string tiponegocio, object userState) {
            if ((this.ObtenerPyPOperationCompleted == null)) {
                this.ObtenerPyPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPyPOperationCompleted);
            }
            this.InvokeAsync("ObtenerPyP", new object[] {
                        nemotecnico,
                        tiponegocio}, this.ObtenerPyPOperationCompleted, userState);
        }
        
        private void OnObtenerPyPOperationCompleted(object arg) {
            if ((this.ObtenerPyPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPyPCompleted(this, new ObtenerPyPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerSegmentosComision", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerSegmentosComision(string TipoComision) {
            object[] results = this.Invoke("ObtenerSegmentosComision", new object[] {
                        TipoComision});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSegmentosComisionAsync(string TipoComision) {
            this.ObtenerSegmentosComisionAsync(TipoComision, null);
        }
        
        /// <remarks/>
        public void ObtenerSegmentosComisionAsync(string TipoComision, object userState) {
            if ((this.ObtenerSegmentosComisionOperationCompleted == null)) {
                this.ObtenerSegmentosComisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSegmentosComisionOperationCompleted);
            }
            this.InvokeAsync("ObtenerSegmentosComision", new object[] {
                        TipoComision}, this.ObtenerSegmentosComisionOperationCompleted, userState);
        }
        
        private void OnObtenerSegmentosComisionOperationCompleted(object arg) {
            if ((this.ObtenerSegmentosComisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSegmentosComisionCompleted(this, new ObtenerSegmentosComisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerParametrosConfiguracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerParametrosConfiguracion() {
            object[] results = this.Invoke("ObtenerParametrosConfiguracion", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerParametrosConfiguracionAsync() {
            this.ObtenerParametrosConfiguracionAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerParametrosConfiguracionAsync(object userState) {
            if ((this.ObtenerParametrosConfiguracionOperationCompleted == null)) {
                this.ObtenerParametrosConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerParametrosConfiguracionOperationCompleted);
            }
            this.InvokeAsync("ObtenerParametrosConfiguracion", new object[0], this.ObtenerParametrosConfiguracionOperationCompleted, userState);
        }
        
        private void OnObtenerParametrosConfiguracionOperationCompleted(object arg) {
            if ((this.ObtenerParametrosConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerParametrosConfiguracionCompleted(this, new ObtenerParametrosConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerCierresPorInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerCierresPorInstrumento(string fecha, string nemotecnico) {
            object[] results = this.Invoke("ObtenerCierresPorInstrumento", new object[] {
                        fecha,
                        nemotecnico});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCierresPorInstrumentoAsync(string fecha, string nemotecnico) {
            this.ObtenerCierresPorInstrumentoAsync(fecha, nemotecnico, null);
        }
        
        /// <remarks/>
        public void ObtenerCierresPorInstrumentoAsync(string fecha, string nemotecnico, object userState) {
            if ((this.ObtenerCierresPorInstrumentoOperationCompleted == null)) {
                this.ObtenerCierresPorInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCierresPorInstrumentoOperationCompleted);
            }
            this.InvokeAsync("ObtenerCierresPorInstrumento", new object[] {
                        fecha,
                        nemotecnico}, this.ObtenerCierresPorInstrumentoOperationCompleted, userState);
        }
        
        private void OnObtenerCierresPorInstrumentoOperationCompleted(object arg) {
            if ((this.ObtenerCierresPorInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCierresPorInstrumentoCompleted(this, new ObtenerCierresPorInstrumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/SolicitudDeCancelación", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SolicitudDeCancelación(string idusuario, long idorden, string tipoorden, string tiponegocio) {
            object[] results = this.Invoke("SolicitudDeCancelación", new object[] {
                        idusuario,
                        idorden,
                        tipoorden,
                        tiponegocio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitudDeCancelaciónAsync(string idusuario, long idorden, string tipoorden, string tiponegocio) {
            this.SolicitudDeCancelaciónAsync(idusuario, idorden, tipoorden, tiponegocio, null);
        }
        
        /// <remarks/>
        public void SolicitudDeCancelaciónAsync(string idusuario, long idorden, string tipoorden, string tiponegocio, object userState) {
            if ((this.SolicitudDeCancelaciónOperationCompleted == null)) {
                this.SolicitudDeCancelaciónOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitudDeCancelaciónOperationCompleted);
            }
            this.InvokeAsync("SolicitudDeCancelación", new object[] {
                        idusuario,
                        idorden,
                        tipoorden,
                        tiponegocio}, this.SolicitudDeCancelaciónOperationCompleted, userState);
        }
        
        private void OnSolicitudDeCancelaciónOperationCompleted(object arg) {
            if ((this.SolicitudDeCancelaciónCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitudDeCancelaciónCompleted(this, new SolicitudDeCancelaciónCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ColocarOrden", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ColocarOrden(string idusuario, string tiponegocio, string tipoOrden, string instrumento, long cantidad, decimal precio, decimal comision, decimal total, string fechavigencia, int cuentaDeceval, string ipcliente) {
            object[] results = this.Invoke("ColocarOrden", new object[] {
                        idusuario,
                        tiponegocio,
                        tipoOrden,
                        instrumento,
                        cantidad,
                        precio,
                        comision,
                        total,
                        fechavigencia,
                        cuentaDeceval,
                        ipcliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ColocarOrdenAsync(string idusuario, string tiponegocio, string tipoOrden, string instrumento, long cantidad, decimal precio, decimal comision, decimal total, string fechavigencia, int cuentaDeceval, string ipcliente) {
            this.ColocarOrdenAsync(idusuario, tiponegocio, tipoOrden, instrumento, cantidad, precio, comision, total, fechavigencia, cuentaDeceval, ipcliente, null);
        }
        
        /// <remarks/>
        public void ColocarOrdenAsync(string idusuario, string tiponegocio, string tipoOrden, string instrumento, long cantidad, decimal precio, decimal comision, decimal total, string fechavigencia, int cuentaDeceval, string ipcliente, object userState) {
            if ((this.ColocarOrdenOperationCompleted == null)) {
                this.ColocarOrdenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnColocarOrdenOperationCompleted);
            }
            this.InvokeAsync("ColocarOrden", new object[] {
                        idusuario,
                        tiponegocio,
                        tipoOrden,
                        instrumento,
                        cantidad,
                        precio,
                        comision,
                        total,
                        fechavigencia,
                        cuentaDeceval,
                        ipcliente}, this.ColocarOrdenOperationCompleted, userState);
        }
        
        private void OnColocarOrdenOperationCompleted(object arg) {
            if ((this.ColocarOrdenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ColocarOrdenCompleted(this, new ColocarOrdenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/CambiarContraseña", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CambiarContraseña(string idusuario, string nuevacontrasena) {
            object[] results = this.Invoke("CambiarContraseña", new object[] {
                        idusuario,
                        nuevacontrasena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CambiarContraseñaAsync(string idusuario, string nuevacontrasena) {
            this.CambiarContraseñaAsync(idusuario, nuevacontrasena, null);
        }
        
        /// <remarks/>
        public void CambiarContraseñaAsync(string idusuario, string nuevacontrasena, object userState) {
            if ((this.CambiarContraseñaOperationCompleted == null)) {
                this.CambiarContraseñaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarContraseñaOperationCompleted);
            }
            this.InvokeAsync("CambiarContraseña", new object[] {
                        idusuario,
                        nuevacontrasena}, this.CambiarContraseñaOperationCompleted, userState);
        }
        
        private void OnCambiarContraseñaOperationCompleted(object arg) {
            if ((this.CambiarContraseñaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarContraseñaCompleted(this, new CambiarContraseñaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/ObtenerSaldoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerSaldoCliente(string idusuario) {
            object[] results = this.Invoke("ObtenerSaldoCliente", new object[] {
                        idusuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSaldoClienteAsync(string idusuario) {
            this.ObtenerSaldoClienteAsync(idusuario, null);
        }
        
        /// <remarks/>
        public void ObtenerSaldoClienteAsync(string idusuario, object userState) {
            if ((this.ObtenerSaldoClienteOperationCompleted == null)) {
                this.ObtenerSaldoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSaldoClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerSaldoCliente", new object[] {
                        idusuario}, this.ObtenerSaldoClienteOperationCompleted, userState);
        }
        
        private void OnObtenerSaldoClienteOperationCompleted(object arg) {
            if ((this.ObtenerSaldoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSaldoClienteCompleted(this, new ObtenerSaldoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/Desconexion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Desconexion(string usuario, string clave) {
            object[] results = this.Invoke("Desconexion", new object[] {
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesconexionAsync(string usuario, string clave) {
            this.DesconexionAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void DesconexionAsync(string usuario, string clave, object userState) {
            if ((this.DesconexionOperationCompleted == null)) {
                this.DesconexionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesconexionOperationCompleted);
            }
            this.InvokeAsync("Desconexion", new object[] {
                        usuario,
                        clave}, this.DesconexionOperationCompleted, userState);
        }
        
        private void OnDesconexionOperationCompleted(object arg) {
            if ((this.DesconexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesconexionCompleted(this, new DesconexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/EstaConectado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EstaConectado(string idUsuario) {
            object[] results = this.Invoke("EstaConectado", new object[] {
                        idUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EstaConectadoAsync(string idUsuario) {
            this.EstaConectadoAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void EstaConectadoAsync(string idUsuario, object userState) {
            if ((this.EstaConectadoOperationCompleted == null)) {
                this.EstaConectadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstaConectadoOperationCompleted);
            }
            this.InvokeAsync("EstaConectado", new object[] {
                        idUsuario}, this.EstaConectadoOperationCompleted, userState);
        }
        
        private void OnEstaConectadoOperationCompleted(object arg) {
            if ((this.EstaConectadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstaConectadoCompleted(this, new EstaConectadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AccionesCompletedEventHandler(object sender, AccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PortafolioClienteCompletedEventHandler(object sender, PortafolioClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class PortafolioClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PortafolioClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MovimientoGraficoCompletedEventHandler(object sender, MovimientoGraficoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class MovimientoGraficoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MovimientoGraficoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MovimientoIGBCCompletedEventHandler(object sender, MovimientoIGBCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class MovimientoIGBCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MovimientoIGBCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MovimientoCOLCAPCompletedEventHandler(object sender, MovimientoCOLCAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class MovimientoCOLCAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MovimientoCOLCAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MovimientoCOL20CompletedEventHandler(object sender, MovimientoCOL20CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class MovimientoCOL20CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MovimientoCOL20CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AutenticacionCompletedEventHandler(object sender, AutenticacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AutenticacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtieneCuentasDecevalCompletedEventHandler(object sender, ObtieneCuentasDecevalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtieneCuentasDecevalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneCuentasDecevalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerOrdenesAbiertasCompletedEventHandler(object sender, ObtenerOrdenesAbiertasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerOrdenesAbiertasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerOrdenesAbiertasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerOrdenesDiaCompletedEventHandler(object sender, ObtenerOrdenesDiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerOrdenesDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerOrdenesDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerPyPCompletedEventHandler(object sender, ObtenerPyPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerPyPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPyPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerSegmentosComisionCompletedEventHandler(object sender, ObtenerSegmentosComisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerSegmentosComisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSegmentosComisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerParametrosConfiguracionCompletedEventHandler(object sender, ObtenerParametrosConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerParametrosConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerParametrosConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerCierresPorInstrumentoCompletedEventHandler(object sender, ObtenerCierresPorInstrumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerCierresPorInstrumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCierresPorInstrumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SolicitudDeCancelaciónCompletedEventHandler(object sender, SolicitudDeCancelaciónCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SolicitudDeCancelaciónCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitudDeCancelaciónCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ColocarOrdenCompletedEventHandler(object sender, ColocarOrdenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ColocarOrdenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ColocarOrdenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CambiarContraseñaCompletedEventHandler(object sender, CambiarContraseñaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class CambiarContraseñaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiarContraseñaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerSaldoClienteCompletedEventHandler(object sender, ObtenerSaldoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ObtenerSaldoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSaldoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DesconexionCompletedEventHandler(object sender, DesconexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DesconexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesconexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EstaConectadoCompletedEventHandler(object sender, EstaConectadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class EstaConectadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstaConectadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591