//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataifx.AuctionDesc.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ironman.corredor.local:80/BVC-IngresoAutomaticoOrdenesWeb/sca/BVC-IngresoA" +
            "utomaticoOrdenesWS")]
        public string Dataifx_Trading_Services_WS_BVC_Corredores_BVC_IngresoAutomaticoOrdenesWS_BVC_IngresoAutomaticoOrdenesHttpService {
            get {
                return ((string)(this["Dataifx_Trading_Services_WS_BVC_Corredores_BVC_IngresoAutomaticoOrdenesWS_BVC_Ing" +
                    "resoAutomaticoOrdenesHttpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/AVAcciones/WebServices/PlataformaWeb.asmx")]
        public string WSDisconnect {
            get {
                return ((string)(this["WSDisconnect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1931197286-T24jznk6md6CXKORIjVRC4MzjGHVIbFrI7uxMId")]
        public string oauth_token {
            get {
                return ((string)(this["oauth_token"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5BeSJKtLYD68IKKBqb6Fw4CEzSMUrXWnfE6loN3bMg")]
        public string oauth_token_secret {
            get {
                return ((string)(this["oauth_token_secret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tSCfnGIEl9OUooa4rj4lAA")]
        public string oauth_consumer_key {
            get {
                return ((string)(this["oauth_consumer_key"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MGALm2KpU5ZL7Z9AJssvMTFRCxHMUBlwWbiILb6PtBc")]
        public string oauth_consumer_secret {
            get {
                return ((string)(this["oauth_consumer_secret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/AccionesYValoresWeb/WebServices/PlataformaWeb.asmx")]
        public string Dataifx_Trading_Services_WSDisconnect_PlataformaWeb {
            get {
                return ((string)(this["Dataifx_Trading_Services_WSDisconnect_PlataformaWeb"]));
            }
        }
    }
}
